/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /root/ros_core_ws/src/ros_tutorials/turtlesim/srv/Kill.srv
 *
 */


#ifndef TURTLESIM_MESSAGE_KILL_H
#define TURTLESIM_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <turtlesim/KillRequest.h>
#include <turtlesim/KillResponse.h>


namespace turtlesim
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::turtlesim::Kill&) { return value(); }
};

template<>
struct DataType< ::turtlesim::Kill > {
  static const char* value()
  {
    return "turtlesim/Kill";
  }

  static const char* value(const ::turtlesim::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::KillRequest> should match 
// service_traits::MD5Sum< ::turtlesim::Kill > 
template<>
struct MD5Sum< ::turtlesim::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::KillRequest> should match 
// service_traits::DataType< ::turtlesim::Kill > 
template<>
struct DataType< ::turtlesim::KillRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::KillResponse> should match 
// service_traits::MD5Sum< ::turtlesim::Kill > 
template<>
struct MD5Sum< ::turtlesim::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::KillResponse> should match 
// service_traits::DataType< ::turtlesim::Kill > 
template<>
struct DataType< ::turtlesim::KillResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::Kill >::value();
  }
  static const char* value(const ::turtlesim::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_KILL_H
