#! /usr/bin/perl


# get-classpayth, copyright 2011 by Vincent Fourmond

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.

$file = shift(@ARGV);
open MANIFEST, "unzip -p \"$file\" META-INF/MANIFEST.MF | ";
my $cp = "";
while(my $line = <MANIFEST>) {
    if($line =~ /Class-Path:\s*(.*)/) {
	$cp = $1;
    }
    elsif($cp) {
	
	if($line =~ /^ (.*)/) {
	    $cp .= $1;
	}
	else {
	    last;
	}
    }
}
close MANIFEST;
$cp =~ s/\r//g;
print "$cp\n";

