#!/bin/sh
# Script optimised to run from within dhelp's swish++.conf.
# That means:
# * No error checking on parameters; edit swish++.conf the right way.
# * Spit output only on errors (a line pointing to input file).
#
# $1 = Input file, $2 = Output file

2>/dev/null gzip -dc ${1} > ${2}
EXITVAL=$?
if [ ${EXITVAL} -ne 0 ]; then
	echo "Error decompressing file: ${1}"
fi
exit ${EXITVAL}
