--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Indicates some other unhandled resolver error was encountered.
constants: []

full_name: Resolv::DNS::Config::OtherResolvError
includes: []

instance_methods: []

name: OtherResolvError
superclass: ResolvError
