=head1 NAME

Gtk2::Pango::FontDescription - moved to Pango::FontDescription, kept for backwards compatibility

=cut

=for position DESCRIPTION

=head1 DESCRIPTION

As of Gtk2 1.220, pango bindings are provided by the standalone Pango module.
This namespace is provided for backwards compatibility.  The relevant
documentation moved to Pango and is linked to below.

=cut



=head1 HIERARCHY

  Glib::Boxed
  +----Gtk2::Pango::FontDescription



=cut

=for object Gtk2::Pango::FontDescription
=cut




=head1 SEE ALSO

L<Gtk2>, L<Glib::Boxed>, L<Pango::FontDescription>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

