=head1 NAME

Gtk2::CellRendererToggle - wrapper for GtkCellRendererToggle

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::CellRenderer
                 +----Gtk2::CellRendererToggle



=cut


=head1 METHODS

=head2 cellrenderer = Gtk2::CellRendererToggle-E<gt>B<new> 

=head2 boolean = $toggle-E<gt>B<get_active> 

=head2 $toggle-E<gt>B<set_active> ($setting)

=over

=item * $setting (boolean) 

=back

=head2 boolean = $toggle-E<gt>B<get_radio> 

=head2 $toggle-E<gt>B<set_radio> ($radio)

=over

=item * $radio (boolean) 

=back



=cut


=head1 PROPERTIES

=over

=item 'activatable' (boolean : default true : readable / writable / private)

The toggle button can be activated

=item 'active' (boolean : default false : readable / writable / private)

The toggle state of the button

=item 'inconsistent' (boolean : default false : readable / writable / private)

The inconsistent state of the button

=item 'indicator-size' (integer : default 13 : readable / writable / private)

Size of check or radio indicator

=item 'radio' (boolean : default false : readable / writable / private)

Draw the toggle button as a radio button

=back



=cut


=head1 SIGNALS

=over

=item B<toggled> (Gtk2::CellRendererToggle, string)

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::CellRenderer>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

