=head1 NAME

Gtk2::FileChooser - wrapper for GtkFileChooser

=cut

=head1 HIERARCHY

  Glib::Interface
  +----Gtk2::FileChooser



=cut


=head1 METHODS

=head2 filechooseraction = $chooser-E<gt>B<get_action> 

=head2 $chooser-E<gt>B<set_action> ($action)

=over

=item * $action (Gtk2::FileChooserAction) 

=back

=head2 $chooser-E<gt>B<add_filter> ($filter)

=over

=item * $filter (Gtk2::FileFilter) 

=back

=head2 $chooser-E<gt>B<add_shortcut_folder> ($folder)

=over

=item * $folder (string) 

=back

=head2 $chooser-E<gt>B<add_shortcut_folder_uri> ($folder)

=over

=item * $folder (string) 

=back

=head2 string = $chooser-E<gt>B<get_current_folder> 

=head2 boolean = $chooser-E<gt>B<set_current_folder> ($filename)

=over

=item * $filename (string) 

=back

=head2 string = $chooser-E<gt>B<get_current_folder_uri> 

=head2 boolean = $chooser-E<gt>B<set_current_folder_uri> ($uri)

=over

=item * $uri (string) 

=back

=head2 $chooser-E<gt>B<set_current_name> ($name)

=over

=item * $name (string) 

=back

=head2 boolean = $chooser-E<gt>B<get_do_overwrite_confirmation> 

Since: gtk+ 2.8

=head2 $chooser-E<gt>B<set_do_overwrite_confirmation> ($do_overwrite_confirmation)

=over

=item * $do_overwrite_confirmation (boolean) 

=back

Since: gtk+ 2.8

=head2 widget = $chooser-E<gt>B<get_extra_widget> 

=head2 $chooser-E<gt>B<set_extra_widget> ($extra_widget)

=over

=item * $extra_widget (Gtk2::Widget) 

=back

=head2 string = $chooser-E<gt>B<get_filename> 

=head2 boolean = $chooser-E<gt>B<set_filename> ($filename)

=over

=item * $filename (string) 

=back

=head2 list = $chooser-E<gt>B<get_filenames> 

=head2 filefilter = $chooser-E<gt>B<get_filter> 

=head2 $chooser-E<gt>B<set_filter> ($filter)

=over

=item * $filter (Gtk2::FileFilter) 

=back

=head2 list = $chooser-E<gt>B<list_filters> 

=head2 list = $chooser-E<gt>B<list_shortcut_folder_uris> 

=head2 list = $chooser-E<gt>B<list_shortcut_folders> 

=head2 boolean = $chooser-E<gt>B<get_local_only> 

=head2 $chooser-E<gt>B<set_local_only> ($files_only)

=over

=item * $files_only (boolean) 

=back

=head2 localized file name = $file_chooser-E<gt>B<get_preview_filename> 

=head2 string = $file_chooser-E<gt>B<get_preview_uri> 

=head2 boolean = $chooser-E<gt>B<get_preview_widget_active> 

=head2 $chooser-E<gt>B<set_preview_widget_active> ($active)

=over

=item * $active (boolean) 

=back

=head2 widget = $chooser-E<gt>B<get_preview_widget> 

=head2 $chooser-E<gt>B<set_preview_widget> ($preview_widget)

=over

=item * $preview_widget (Gtk2::Widget) 

=back

=head2 $chooser-E<gt>B<remove_filter> ($filter)

=over

=item * $filter (Gtk2::FileFilter) 

=back

=head2 $chooser-E<gt>B<remove_shortcut_folder> ($folder)

=over

=item * $folder (string) 

=back

=head2 $chooser-E<gt>B<remove_shortcut_folder_uri> ($folder)

=over

=item * $folder (string) 

=back

=head2 $chooser-E<gt>B<select_all> 

=head2 boolean = $chooser-E<gt>B<select_filename> ($filename)

=over

=item * $filename (string) 

=back

=head2 boolean = $chooser-E<gt>B<get_select_multiple> 

=head2 $chooser-E<gt>B<set_select_multiple> ($select_multiple)

=over

=item * $select_multiple (boolean) 

=back

=head2 boolean = $chooser-E<gt>B<select_uri> ($uri)

=over

=item * $uri (string) 

=back

=head2 boolean = $chooser-E<gt>B<get_show_hidden> 

Since: gtk+ 2.6

=head2 $chooser-E<gt>B<set_show_hidden> ($show_hidden)

=over

=item * $show_hidden (boolean) 

=back

Since: gtk+ 2.6

=head2 $chooser-E<gt>B<unselect_all> 

=head2 $chooser-E<gt>B<unselect_filename> ($filename)

=over

=item * $filename (string) 

=back

=head2 $chooser-E<gt>B<unselect_uri> ($uri)

=over

=item * $uri (string) 

=back

=head2 string = $chooser-E<gt>B<get_uri> 

=head2 boolean = $chooser-E<gt>B<set_uri> ($uri)

=over

=item * $uri (string) 

=back

=head2 list = $chooser-E<gt>B<get_uris> 

=head2 boolean = $chooser-E<gt>B<get_use_preview_label> 

=head2 $chooser-E<gt>B<set_use_preview_label> ($use_label)

=over

=item * $use_label (boolean) 

=back



=cut


=head1 PROPERTIES

=over

=item 'action' (Gtk2::FileChooserAction : default "open" : readable / writable / private)

The type of operation that the file selector is performing

=item 'create-folders' (boolean : default true : readable / writable / private)

Whether a file chooser not in open mode will offer the user to create new folders.

=item 'do-overwrite-confirmation' (boolean : default false : readable / writable / private)

Whether a file chooser in save mode will present an overwrite confirmation dialog if necessary.

=item 'extra-widget' (Gtk2::Widget : default undef : readable / writable / private)

Application supplied widget for extra options.

=item 'file-system-backend' (string : default undef : writable / construct-only / private)

Name of file system backend to use

=item 'filter' (Gtk2::FileFilter : default undef : readable / writable / private)

The current filter for selecting which files are displayed

=item 'local-only' (boolean : default true : readable / writable / private)

Whether the selected file(s) should be limited to local file: URLs

=item 'preview-widget' (Gtk2::Widget : default undef : readable / writable / private)

Application supplied widget for custom previews.

=item 'preview-widget-active' (boolean : default true : readable / writable / private)

Whether the application supplied widget for custom previews should be shown.

=item 'select-multiple' (boolean : default false : readable / writable / private)

Whether to allow multiple files to be selected

=item 'show-hidden' (boolean : default false : readable / writable / private)

Whether the hidden files and folders should be displayed

=item 'use-preview-label' (boolean : default true : readable / writable / private)

Whether to display a stock label with the name of the previewed file.

=back



=cut


=head1 SIGNALS

=over

=item B<selection-changed> (Gtk2::FileChooser)

=item B<current-folder-changed> (Gtk2::FileChooser)

=item B<update-preview> (Gtk2::FileChooser)

=item B<file-activated> (Gtk2::FileChooser)

=item GtkFileChooserConfirmation = B<confirm-overwrite> (Gtk2::FileChooser)

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum Gtk2::FileChooserAction



=over

=item * 'open' / 'GTK_FILE_CHOOSER_ACTION_OPEN'

=item * 'save' / 'GTK_FILE_CHOOSER_ACTION_SAVE'

=item * 'select-folder' / 'GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER'

=item * 'create-folder' / 'GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER'

=back


=head2 enum Gtk2::FileChooserError



=over

=item * 'nonexistent' / 'GTK_FILE_CHOOSER_ERROR_NONEXISTENT'

=item * 'bad-filename' / 'GTK_FILE_CHOOSER_ERROR_BAD_FILENAME'

=item * 'already-exists' / 'GTK_FILE_CHOOSER_ERROR_ALREADY_EXISTS'

=item * 'incomplete-hostname' / 'GTK_FILE_CHOOSER_ERROR_INCOMPLETE_HOSTNAME'

=back


=head2 enum GtkFileChooserConfirmation

=over

=item * 'confirm' / 'GTK_FILE_CHOOSER_CONFIRMATION_CONFIRM'

=item * 'accept-filename' / 'GTK_FILE_CHOOSER_CONFIRMATION_ACCEPT_FILENAME'

=item * 'select-again' / 'GTK_FILE_CHOOSER_CONFIRMATION_SELECT_AGAIN'

=back




=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Interface>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

