=head1 NAME

Gtk2::Invisible - wrapper for GtkInvisible

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Invisible



=cut

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable



=cut


=head1 METHODS

=head2 widget = Gtk2::Invisible-E<gt>B<new> 

=head2 widget = Gtk2::Invisible-E<gt>B<new_for_screen> ($screen)

=over

=item * $screen (Gtk2::Gdk::Screen) 

=back

Since: gtk+ 2.2

=head2 screen = $invisible-E<gt>B<get_screen> 

Since: gtk+ 2.2

=head2 $invisible-E<gt>B<set_screen> ($screen)

=over

=item * $screen (Gtk2::Gdk::Screen) 

=back

Since: gtk+ 2.2



=cut


=head1 PROPERTIES

=over

=item 'screen' (Gtk2::Gdk::Screen : default undef : readable / writable / private)

The screen where this window will be displayed

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

