=head1 NAME

Gtk2::MenuItem - wrapper for GtkMenuItem

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Container
                      +----Gtk2::Bin
                           +----Gtk2::Item
                                +----Gtk2::MenuItem



=cut

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable
  Glib::Object::_Unregistered::GtkActivatable



=cut


=head1 METHODS

=head2 widget = Gtk2::MenuItem-E<gt>B<new> ($label=undef)

=over

=item * $label (string) 

=back

=head2 widget = Gtk2::MenuItem-E<gt>B<new_with_label> ($label=undef)

=over

=item * $label (string) 

=back

=head2 widget = Gtk2::MenuItem-E<gt>B<new_with_mnemonic> ($label=undef)

=over

=item * $label (string) 

=back

=head2 string = $menu_item-E<gt>B<get_accel_path> 

Since: gtk+ 2.14

=head2 $menu_item-E<gt>B<set_accel_path> ($accel_path)

=over

=item * $accel_path (string) 

=back

=head2 $menu_item-E<gt>B<activate> 

=head2 $menu_item-E<gt>B<deselect> 

=head2 $menu_item-E<gt>B<remove_submenu> 

=head2 boolean = $menu_item-E<gt>B<get_right_justified> 

=head2 $menu_item-E<gt>B<set_right_justified> ($right_justified)

=over

=item * $right_justified (boolean) 

=back

=head2 $menu_item-E<gt>B<select> 

=head2 widget or undef = $menu_item-E<gt>B<get_submenu> 

=head2 $menu_item-E<gt>B<set_submenu> ($submenu)

=over

=item * $submenu (Gtk2::Widget or undef) 

=back

=head2 $menu_item-E<gt>B<toggle_size_allocate> ($allocation)

=over

=item * $allocation (integer) 

=back

=head2 requisition = $menu_item-E<gt>B<toggle_size_request> 



=cut


=head1 PROPERTIES

=over

=item 'accel-path' (string : default undef : readable / writable / private)

Sets the accelerator path of the menu item

=item 'label' (string : default "" : readable / writable / private)

The text for the child label

=item 'right-justified' (boolean : default false : readable / writable / private)

Sets whether the menu item appears justified at the right side of a menu bar

=item 'submenu' (Gtk2::Menu : default undef : readable / writable / private)

The submenu attached to the menu item, or NULL if it has none

=item 'use-underline' (boolean : default false : readable / writable / private)

If set, an underline in the text indicates the next character should be used for the mnemonic accelerator key

=back



=cut


=head1 SIGNALS

=over

=item B<activate> (Gtk2::MenuItem)

=item B<activate-item> (Gtk2::MenuItem)

=item B<toggle-size-request> (Gtk2::MenuItem, gpointer)

=item B<toggle-size-allocate> (Gtk2::MenuItem, integer)

=item B<submenu-added> (Gtk2::MenuItem, Gtk2::Widget)

=item B<submenu-removed> (Gtk2::MenuItem)

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>, L<Gtk2::Container>, L<Gtk2::Bin>, L<Gtk2::Item>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

