=head1 NAME

Gtk2::MenuToolButton - wrapper for GtkMenuToolButton

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Container
                      +----Gtk2::Bin
                           +----Gtk2::ToolItem
                                +----Gtk2::ToolButton
                                     +----Gtk2::MenuToolButton



=cut

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable
  Glib::Object::_Unregistered::GtkActivatable



=cut


=head1 METHODS

=head2 toolitem = Gtk2::MenuToolButton-E<gt>B<new> ($icon_widget, $label)

=over

=item * $icon_widget (Gtk2::Widget or undef) 

=item * $label (string or undef) 

=back

=head2 toolitem = Gtk2::MenuToolButton-E<gt>B<new_from_stock> ($stock_id)

=over

=item * $stock_id (string) 

=back

=head2 $button-E<gt>B<set_arrow_tooltip_markup> ($markup)

=over

=item * $markup (string or undef) 

=back

Since: gtk+ 2.12

=head2 $button-E<gt>B<set_arrow_tooltip> ($tooltips, $tip_text, $tip_private)

=over

=item * $tooltips (Gtk2::Tooltips) 

=item * $tip_text (string) 

=item * $tip_private (string) 

=back

=head2 $button-E<gt>B<set_arrow_tooltip_text> ($text)

=over

=item * $text (string or undef) 

=back

Since: gtk+ 2.12

=head2 widget or undef = $button-E<gt>B<get_menu> 

=head2 $button-E<gt>B<set_menu> ($menu)

=over

=item * $menu (Gtk2::Widget or undef) 

=back



=cut


=head1 PROPERTIES

=over

=item 'menu' (Gtk2::Menu : default undef : readable / writable / private)

The dropdown menu

=back



=cut


=head1 SIGNALS

=over

=item B<show-menu> (Gtk2::MenuToolButton)

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>, L<Gtk2::Container>, L<Gtk2::Bin>, L<Gtk2::ToolItem>, L<Gtk2::ToolButton>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

