=head1 NAME

Gtk2::MenuShell - wrapper for GtkMenuShell

=cut

=head1 HIERARCHY

  Glib::Object
  +----Glib::InitiallyUnowned
       +----Gtk2::Object
            +----Gtk2::Widget
                 +----Gtk2::Container
                      +----Gtk2::MenuShell



=cut

=head1 INTERFACES

  Glib::Object::_Unregistered::AtkImplementorIface
  Gtk2::Buildable



=cut


=head1 METHODS

=head2 $menu_shell-E<gt>B<activate_item> ($menu_item, $force_deactivate)

=over

=item * $menu_item (Gtk2::Widget) 

=item * $force_deactivate (boolean) 

=back

=head2 $menu_shell-E<gt>B<append> ($child)

=over

=item * $child (Gtk2::Widget) 

=back

=head2 $menu_shell-E<gt>B<cancel> 

Since: gtk+ 2.4

=head2 $menu_shell-E<gt>B<deactivate> 

=head2 $menu_shell-E<gt>B<deselect> 

=head2 $menu_shell-E<gt>B<insert> ($child, $position)

=over

=item * $child (Gtk2::Widget) 

=item * $position (integer) 

=back

=head2 $menu_shell-E<gt>B<prepend> ($child)

=over

=item * $child (Gtk2::Widget) 

=back

=head2 $menu_shell-E<gt>B<select_first> ($search_sensitive)

=over

=item * $search_sensitive (boolean) 

=back

Since: gtk+ 2.2

=head2 $menu_shell-E<gt>B<select_item> ($menu_item)

=over

=item * $menu_item (Gtk2::Widget) 

=back

=head2 boolean = $menu_shell-E<gt>B<get_take_focus> 

Since: gtk+ 2.8

=head2 $menu_shell-E<gt>B<set_take_focus> ($take_focus)

=over

=item * $take_focus (boolean) 

=back

Since: gtk+ 2.8



=cut


=head1 PROPERTIES

=over

=item 'take-focus' (boolean : default true : readable / writable / private)

A boolean that determines whether the menu grabs the keyboard focus

=item 'ubuntu-local' (boolean : default false : readable / writable / private)

Determines whether the menu is local

=back



=cut


=head1 SIGNALS

=over

=item B<cancel> (Gtk2::MenuShell)

=item B<deactivate> (Gtk2::MenuShell)

=item B<selection-done> (Gtk2::MenuShell)

=item B<move-current> (Gtk2::MenuShell, Gtk2::MenuDirectionType)

=item B<activate-current> (Gtk2::MenuShell, boolean)

=item B<cycle-focus> (Gtk2::MenuShell, Gtk2::DirectionType)

=item boolean = B<move-selected> (Gtk2::MenuShell, integer)

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum Gtk2::DirectionType

=over

=item * 'tab-forward' / 'GTK_DIR_TAB_FORWARD'

=item * 'tab-backward' / 'GTK_DIR_TAB_BACKWARD'

=item * 'up' / 'GTK_DIR_UP'

=item * 'down' / 'GTK_DIR_DOWN'

=item * 'left' / 'GTK_DIR_LEFT'

=item * 'right' / 'GTK_DIR_RIGHT'

=back


=head2 enum Gtk2::MenuDirectionType

=over

=item * 'parent' / 'GTK_MENU_DIR_PARENT'

=item * 'child' / 'GTK_MENU_DIR_CHILD'

=item * 'next' / 'GTK_MENU_DIR_NEXT'

=item * 'prev' / 'GTK_MENU_DIR_PREV'

=back




=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Glib::InitiallyUnowned>, L<Gtk2::Object>, L<Gtk2::Widget>, L<Gtk2::Container>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

