=head1 NAME

Gtk2::Selection

=cut

=for object Gtk2::Selection
=cut




=head1 METHODS

=head2 boolean = Gtk2::Selection-E<gt>B<owner_set> ($widget, $selection, $time_)

=over

=item * $widget (Gtk2::Widget or undef) 

=item * $selection (Gtk2::Gdk::Atom) 

=item * $time_ (unsigned) 

=back

=head2 boolean = Gtk2::Selection-E<gt>B<owner_set_for_display> ($display, $widget, $selection, $time_)

=over

=item * $display (Gtk2::Gdk::Display) 

=item * $widget (Gtk2::Widget or undef) 

=item * $selection (Gtk2::Gdk::Atom) 

=item * $time_ (unsigned) 

=back

Since: gtk+ 2.2

=head2 boolean = Gtk2-E<gt>B<targets_include_image> ($writable, $first_target_atom, ...)

=over

=item * $writable (boolean) 

=item * $first_target_atom (Gtk2::Gdk::Atom) 

=item * ... (list) 

=back

Since: gtk+ 2.10

=head2 boolean = Gtk2-E<gt>B<targets_include_rich_text> ($buffer, $first_target_atom, ...)

=over

=item * $buffer (Gtk2::TextBuffer) 

=item * $first_target_atom (Gtk2::Gdk::Atom) 

=item * ... (list) 

=back

Since: gtk+ 2.10

=head2 boolean = Gtk2-E<gt>B<targets_include_text> ($first_target_atom, ...)

=over

=item * $first_target_atom (Gtk2::Gdk::Atom) 

=item * ... (list) 

=back

Since: gtk+ 2.10

=head2 boolean = Gtk2-E<gt>B<targets_include_uri> ($first_target_atom, ...)

=over

=item * $first_target_atom (Gtk2::Gdk::Atom) 

=item * ... (list) 

=back

Since: gtk+ 2.10



=cut


=head1 SEE ALSO

L<Gtk2>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

