=head1 NAME

Gtk2::TextTagTable - wrapper for GtkTextTagTable

=cut

=head1 HIERARCHY

  Glib::Object
  +----Gtk2::TextTagTable



=cut

=head1 INTERFACES

  Gtk2::Buildable



=cut


=head1 METHODS

=head2 texttagtable = Gtk2::TextTagTable-E<gt>B<new> 

=head2 $table-E<gt>B<add> ($tag)

=over

=item * $tag (Gtk2::TextTag) 

=back

=head2 $table-E<gt>B<foreach> ($callback, $callback_data=undef)

=over

=item * $callback (scalar) 

=item * $callback_data (scalar) 

=back

=head2 texttag = $table-E<gt>B<lookup> ($name)

=over

=item * $name (string) 

=back

=head2 $table-E<gt>B<remove> ($tag)

=over

=item * $tag (Gtk2::TextTag) 

=back

=head2 integer = $table-E<gt>B<get_size> 



=cut


=head1 SIGNALS

=over

=item B<tag-changed> (Gtk2::TextTagTable, Gtk2::TextTag, boolean)

=item B<tag-added> (Gtk2::TextTagTable, Gtk2::TextTag)

=item B<tag-removed> (Gtk2::TextTagTable, Gtk2::TextTag)

=back



=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

