/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /root/ros_core_ws/src/ros_tutorials/rospy_tutorials/srv/BadTwoInts.srv
 *
 */


#ifndef ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H
#define ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <rospy_tutorials/BadTwoIntsRequest.h>
#include <rospy_tutorials/BadTwoIntsResponse.h>


namespace rospy_tutorials
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace rospy_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rospy_tutorials::BadTwoInts > {
  static const char* value()
  {
    return "60962375a49bd6746d7c85dff75ebb9c";
  }

  static const char* value(const ::rospy_tutorials::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::rospy_tutorials::BadTwoInts > {
  static const char* value()
  {
    return "rospy_tutorials/BadTwoInts";
  }

  static const char* value(const ::rospy_tutorials::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::rospy_tutorials::BadTwoIntsRequest> should match 
// service_traits::MD5Sum< ::rospy_tutorials::BadTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorials::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorials::BadTwoIntsRequest> should match 
// service_traits::DataType< ::rospy_tutorials::BadTwoInts > 
template<>
struct DataType< ::rospy_tutorials::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rospy_tutorials::BadTwoIntsResponse> should match 
// service_traits::MD5Sum< ::rospy_tutorials::BadTwoInts > 
template<>
struct MD5Sum< ::rospy_tutorials::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rospy_tutorials::BadTwoIntsResponse> should match 
// service_traits::DataType< ::rospy_tutorials::BadTwoInts > 
template<>
struct DataType< ::rospy_tutorials::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::rospy_tutorials::BadTwoInts >::value();
  }
  static const char* value(const ::rospy_tutorials::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSPY_TUTORIALS_MESSAGE_BADTWOINTS_H
