(defun codify ()
 (interactive)
 (save-excursion
  (catch 'loop
    (while t
     (cond ((looking-at "\\\\end{lisp}") (throw 'loop t))
	   ((looking-at "\\$")
	    (forward-char)
	    (while (not (looking-at "\\$")) (forward-char))
	    (forward-char))
	   ((looking-at "#") (insert "\\") (forward-char 1))
	   ((looking-at "&") (insert "\\") (forward-char 1))
	   ((looking-at "\\. ") (forward-char) (insert "\\") (forward-char 1))
	   ((looking-at "! ") (forward-char) (insert "\\") (forward-char 1))
	   ((looking-at "\\? ") (forward-char) (insert "\\") (forward-char 1))
	   ((looking-at "\"")
	    (delete-char 1)
	    (insert "\\symbol{34}"))
	   ((looking-at "%")
	    (delete-char 1)
	    (insert "\\symbol{37}"))
	   ((looking-at "\\\\")
	    (delete-char 1)
	    (insert "\\symbol{92}"))
	   ((looking-at "_")
	    (delete-char 1)
	    (insert "\\symbol{95}"))
	   ((looking-at "{")
	    (delete-char 1)
	    (insert "\\symbol{123}"))
	   ((looking-at "}")
	    (delete-char 1)
	    (insert "\\symbol{125}"))
	   ((looking-at "~")
	    (delete-char 1)
	    (insert "\\symbol{126}"))
	   (t (forward-char))))))
 (save-excursion
  (catch 'loop
    (while t
     (beginning-of-line)
     (if (looking-at "\\\\end{lisp}") (throw 'loop t))
     (let ((bol (point))
	   (n 0))
      (back-to-indentation)
      (cond ((looking-at "^$") (insert "\\ \\\\"))
	    (t (while (not (= (point) bol))
		(backward-delete-char-untabify 1)
		(setq n (+ n 1)))
	       (while (> n 0) (insert "\\ ") (setq n (- n 1)))
	       (end-of-line)
	       (insert "\\\\"))))
     (forward-line)))))

(defun uncodify ()
 (interactive)
 (save-excursion
  (catch 'loop
    (while t
     (beginning-of-line)
     (if (looking-at "\\\\end{lisp}") (throw 'loop t))
     (while (looking-at "\\\\ ") (delete-char 1) (forward-char))
     (end-of-line)
     (backward-char 2)
     (if (looking-at "\\\\\\\\") (delete-char 2))
     (forward-line))))
 (save-excursion
  (catch 'loop
    (while t
     (cond ((looking-at "\\\\end{lisp}") (throw 'loop t))
	   ((looking-at "\\$")
	    (forward-char)
	    (while (not (looking-at "\\$")) (forward-char))
	    (forward-char))
	   ((looking-at "\\\\#") (delete-char 1) (forward-char))
	   ((looking-at "\\\\&") (delete-char 1) (forward-char))
	   ((looking-at "\\.\\\\ ")
	    (forward-char)
	    (delete-char 1)
	    (forward-char))
	   ((looking-at "!\\\\ ")
	    (forward-char)
	    (delete-char 1)
	    (forward-char))
	   ((looking-at "\\?\\\\ ")
	    (forward-char)
	    (delete-char 1)
	    (forward-char))
	   ((looking-at "\\\\symbol{34}")
	    (delete-char 11)
	    (insert "\""))
	   ((looking-at "\\\\symbol{37}")
	    (delete-char 11)
	    (insert "%"))
	   ((looking-at "\\\\symbol{92}")
	    (delete-char 11)
	    (insert "\\"))
	   ((looking-at "\\\\symbol{95}")
	    (delete-char 11)
	    (insert "_"))
	   ((looking-at "\\\\symbol{123}")
	    (delete-char 12)
	    (insert "{"))
	   ((looking-at "\\\\symbol{125}")
	    (delete-char 12)
	    (insert "}"))
	   ((looking-at "\\\\symbol{126}")
	    (delete-char 12)
	    (insert "~"))
	   (t (forward-char)))))))
