(define-key global-map "\C-x<"	  'move-line-to-top-of-window)
(define-key global-map "\C-x>"	  'move-line-to-bottom-of-window)
(define-key global-map "\C-\M-q"  'indent-sexp)
(define-key global-map "\C-\M-z"  'save-buffers-kill-emacs)
(define-key global-map "\C-\M-r"  'reposition-window-around-defun)
(define-key global-map "\C-\M-l"  'switch-to-other-buffer)
(define-key global-map "\C-cs"    'word-search-forward)
(define-key global-map "\C-cr"    'word-search-backward)
(define-key global-map "\C-cT"    'select-shell)
(define-key global-map "\C-cM"    'mhs-rmail)
(define-key global-map "\C-cE"    'select-editor)
(define-key global-map "\C-cF"    'select-editor) ;for now
(define-key global-map "\C-x\C-b" 'my-list-buffers)
(define-key global-map "\C-x\C-s" 'my-save-buffer)
(define-key global-map "\M-W"     'browse-url-at-point)
(define-key Buffer-menu-mode-map " " 'Buffer-menu-select)
