;;;{Fri Jun 14 19:00:51 1991}

(defun current-date-string ()
 (let* ((string (current-time-string))
        (date (substring string 8 10))
	(month (substring string 4 7))
        (year (substring string 20 24))
        (long-month (cond ((equal month "Jan") "January")
			  ((equal month "Feb") "February")
			  ((equal month "Mar") "March")
			  ((equal month "Apr") "April")
			  ((equal month "May") "May")
			  ((equal month "Jun") "June")
			  ((equal month "Jul") "July")
			  ((equal month "Aug") "August")
			  ((equal month "Sep") "September")
			  ((equal month "Oct") "October")
			  ((equal month "Nov") "November")
			  ((equal month "Dec") "December")
			  (t "XXX"))))
  (if (equal (substring date 0 1) " ")
      (concat long-month date "\, " year)
      (concat long-month " " date "\, " year))))

(defun current-date-time-string ()
 (let* ((string (current-time-string))
	(day (substring string 0 3))
        (date (substring string 8 10))
	(month (substring string 4 7))
        (year (substring string 20 24))
	(time (substring string 11 19))
        (long-day (cond ((equal day "Sun") "Sunday")
			((equal day "Mon") "Monday")
			((equal day "Tue") "Tuesday")
			((equal day "Wed") "Wednesday")
			((equal day "Thu") "Thursday")
			((equal day "Fri") "Friday")
			((equal day "Sat") "Saturday")
			(t "XXX")))
        (long-month (cond ((equal month "Jan") "January")
			  ((equal month "Feb") "February")
			  ((equal month "Mar") "March")
			  ((equal month "Apr") "April")
			  ((equal month "May") "May")
			  ((equal month "Jun") "June")
			  ((equal month "Jul") "July")
			  ((equal month "Aug") "August")
			  ((equal month "Sep") "September")
			  ((equal month "Oct") "October")
			  ((equal month "Nov") "November")
			  ((equal month "Dec") "December")
			  (t "XXX")))
	(timezone "EDT"))
  (if (equal (substring date 0 1) " ")
      (concat
       long-day "\," date "--" long-month "--" year " " time " " timezone)
      (concat
       long-day "\, " date "--" long-month "--" year " " time " " timezone))))

(defun set-latex-last-edit-date ()
 (save-excursion
  (goto-line 0)
  (replace-regexp "\\(LastEditDate}\\)\\({.*}\\)"
                  (concat "\\1{" (current-date-string) "}")))
 nil)

(defun set-latex-last-edit-time ()
 (save-excursion
  (goto-line 0)
  (replace-regexp "\\(LastEditTime}\\)\\({.*}\\)"
                  (concat "\\1{" (current-date-time-string) "}")))
 nil)

(defun my-save-buffer ()
 (interactive)
 (cond ((buffer-modified-p)
	(set-latex-last-edit-date)
	(set-latex-last-edit-time)
	(save-buffer))
       (t (save-buffer))))
