;;; Changed scheme-indent-hook to scheme-indent-function for emacs-19.
(require 'scheme)
(require 'ilisp)
;;; Decrease the default indentation for function bodies.
(setq scheme-body-indent 1)
(put 'when 'scheme-indent-function 1)
(put 'unless 'scheme-indent-function 1)
(put 'syntax-rules 'scheme-indent-function 1)
(put 'eval-when 'scheme-indent-function 1)
(put 'with-font 'scheme-indent-function 1)
(put 'call-with-postscript-file 'scheme-indent-function 1)
(put 'parallel-do 'scheme-indent-function 2)
(define-key scheme-mode-map "\r" 'newline-and-indent)
(define-key scheme-mode-map "\C-zl" 'load-file-lisp)
(define-key scheme-mode-map "\C-zc" 'eval-defun-lisp)
(define-key scheme-mode-map "\C-ze" 'eval-defun-lisp)
(define-key scheme-mode-map "\C-z\C-c" 'eval-defun-and-go-lisp)
(define-key scheme-mode-map "\C-z\C-e" 'eval-defun-and-go-lisp)
(define-key scheme-mode-map "\C-z)" 'find-unbalanced-lisp)
