#!/bin/sh

set -e

dpkg-maintscript-helper rm_conffile /etc/init/alsa-mixer-save.conf \
	1.0.23-2ubuntu3.4 -- "$@"

case "$1" in
  configure)
	# Rename /etc/modprobe.d/sound
	S="/etc/modprobe.d/sound"
	if [ -f "$S" ]
	  then mv "$S" "$S.conf"
	fi
	;;
  abort-upgrade|abort-remove|abort-deconfigure)
	# Nothing to do because we didn't take any action in the prerm
	;;
  *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac


