#!/bin/sh
set -e
# Automatically added by dh_installcatalogs
if [ "$1" = "configure" ]; then
	rm -f /etc/sgml/docbook-dsssl.cat
	for ordcat in /usr/share/sgml/docbook/stylesheet/dsssl/modular/catalog /usr/share/sgml/docbook/stylesheet/dsssl/modular/common/catalog; do
		update-catalog --quiet --add /etc/sgml/docbook-dsssl.cat ${ordcat}
	done
	update-catalog --quiet --add --super /etc/sgml/docbook-dsssl.cat
fi
# End automatically added section
