#!/bin/sh
set -e
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/etc/bash_completion.d/gdbus-bash-completion.sh 2.31.8-0ubuntu2 libglib2.0-bin -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/etc/bash_completion.d/gsettings-bash-completion.sh 2.31.8-0ubuntu2 libglib2.0-bin -- "$@"
# End automatically added section
