#!/bin/sh

set -e

# Update the configuration file (/usr/lib/graphviz/config6)
# Needed for the plugins too
if [ -x /usr/sbin/libgvc5-config-update ]; then
	libgvc5-config-update -c
fi

# Remove the old configuration file if present, see README.Debian-packaging
# Needed only in libgraphivzN
if [ -f /usr/lib/graphviz/config ]; then
	rm -f /usr/lib/graphviz/config
fi

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section

