#! /bin/sh -e

case "$1" in
    remove|purge)
        # only purge if no other library is installed.
        if [ -z "$(ls /usr/lib/libgcj.so.12* 2>/dev/null)" ]; then
	    rm -f /var/lib/gcj-4.6/classmap.db
	    rmdir --ignore-fail-on-non-empty /var/lib/gcj-4.6 2>/dev/null || true
	fi
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section

