#!/bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile; then
  dpkg-maintscript-helper mv_conffile \
    /etc/lightdm/lightdm-gtk-greeter.conf \
    /etc/lightdm/lightdm-gtk-greeter-ubuntu.conf \
    1.0.0-0ubuntu1 -- "$@"
fi    

case "$1" in
  remove|purge)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
      /usr/lib/lightdm/lightdm-set-defaults --remove --greeter=lightdm-gtk-greeter || true
    fi
  ;;
esac



exit 0
