#!/bin/sh -e

set -e

case "$1" in
  remove|purge)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
      /usr/lib/lightdm/lightdm-set-defaults --remove --session=Lubuntu || true
      /usr/lib/lightdm/lightdm-set-defaults --remove --greeter=lightdm-gtk-greeter || true
    fi
    ;;
esac


# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/xdg/pcmanfm/lubuntu.conf /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf 0.15 -- "$@"
# End automatically added section

exit 0
