=head1 NAME

Mail::Message::Body::Multipart - body of a message with attachments

=head1 INHERITANCE

 Mail::Message::Body::Multipart
   is a Mail::Message::Body
   is a Mail::Reporter

=head1 SYNOPSIS

 See Mail::Message::Body

 if($body->isMultipart) {
    my @attachments = $body->parts;
    my $attachment3 = $body->part(2);
    my $before      = $body->preamble;
    my $after       = $body->epilogue;
    $body->part(1)->delete;
 }

=head1 DESCRIPTION

The body (content) of a message can be stored in various ways.  In this
manual-page you find the description of extra functionality you have
when a message contains attachments (parts).

=head1 OVERLOADED

=over 4

=item overload: B<"">

See L<Mail::Message::Body/"OVERLOADED">

=item overload: B<'==' and '!='>

See L<Mail::Message::Body/"OVERLOADED">

=item overload: B<@{}>

See L<Mail::Message::Body/"OVERLOADED">

=item overload: B<bool>

See L<Mail::Message::Body/"OVERLOADED">

=back

=head1 METHODS

=head2 Constructors

=over 4

=item $obj-E<gt>B<clone>

See L<Mail::Message::Body/"Constructors">

=item Mail::Message::Body::Multipart-E<gt>B<new>(OPTIONS)

 -Option           --Defined in     --Default
  based_on           Mail::Message::Body  undef
  boundary                            undef
  charset            Mail::Message::Body  'PERL' or <undef>
  checked            Mail::Message::Body  <false>
  data               Mail::Message::Body  undef
  description        Mail::Message::Body  undef
  disposition        Mail::Message::Body  undef
  eol                Mail::Message::Body  'NATIVE'
  epilogue                            ''
  file               Mail::Message::Body  undef
  log                Mail::Reporter   'WARNINGS'
  message            Mail::Message::Body  undef
  mime_type          Mail::Message::Body  'multipart/mixed'
  modified           Mail::Message::Body  <false>
  parts                               undef
  preamble                            undef
  trace              Mail::Reporter   'WARNINGS'
  transfer_encoding  Mail::Message::Body  'none'

=over 2

=item based_on => BODY

=item boundary => STRING

Separator to be used between parts of the message.  This separator must
be unique in case the message contains nested multiparts (which are not
unusual).  If C<undef>, a nice unique boundary will be generated.

=item charset => CHARSET|'PERL'

=item checked => BOOLEAN

=item data => ARRAY-OF-LINES | STRING

=item description => STRING|FIELD

=item disposition => STRING|FIELD

=item eol => 'CR'|'LF'|'CRLF'|'NATIVE'

=item epilogue => BODY|STRING

The text which is included in the main body after the final boundary.  This
is usually empty, and has no meaning.

Provide a BODY object or a STRING which will automatically translated
into a C<text/plain> body.

=item file => FILENAME|FILEHANDLE|IOHANDLE

=item log => LEVEL

=item message => MESSAGE

=item mime_type => STRING|FIELD|MIME

=item modified => BOOLEAN

=item parts => ARRAY-OF-(MESSAGES|BODIES)

Specifies an initial list of parts in this body.  These may be full
MESSAGES, or BODIES which transformed into messages before use.  Each
message is coerced into a L<Mail::Message::Part|Mail::Message::Part> object.

MIME::Entity and L<Mail::Internet|Mail::Internet> objects are acceptable in the
list, because they are coercible into L<Mail::Message::Part|Mail::Message::Part>'s.  Values
of C<undef> will be skipped silently.

=item preamble => BODY|STRING

The text which is included in the body before the first part.  It is
common use to include a text to warn the user that the message is a
multipart.  However, this was useful in earlier days: most mail
agents are very capable in warning the user themselves.

Provide a BODY object or a STRING which will automatically translated
into a text/plain body.

=item trace => LEVEL

=item transfer_encoding => STRING|FIELD

=back

example: 

 my $intro = Mail::Message::Body->new(data => ['part one']);
 my $pgp   = Mail::Message::Body->new(data => ['part three']);

 my $body  = Mail::Message::Body::Multipart->new
   ( boundary => time . '--it-s-mine'
   , preamble => "This is a multi-part message in MIME format.\n\n"
   , parts    => [ $intro, $folder->message(3)->decoded, $pgp ]
   );

=back

=head2 Constructing a body

=over 4

=item $obj-E<gt>B<attach>(MESSAGES|BODIES)

Attach a list of MESSAGES to this multipart.  A new body is returned.
When you specify BODIES, they will first be translated into
real messages.  MIME::Entity and L<Mail::Internet|Mail::Internet> objects may be
specified too.  In any case, the parts will be coerced into
L<Mail::Message::Part|Mail::Message::Part>'s.

=item $obj-E<gt>B<check>

See L<Mail::Message::Body::Encode/"Constructing a body">

=item $obj-E<gt>B<concatenate>(COMPONENTS)

See L<Mail::Message::Body::Construct/"Constructing a body">

=item $obj-E<gt>B<decoded>(OPTIONS)

See L<Mail::Message::Body/"Constructing a body">

=item $obj-E<gt>B<encode>(OPTIONS)

See L<Mail::Message::Body::Encode/"Constructing a body">

=item $obj-E<gt>B<encoded>

See L<Mail::Message::Body::Encode/"Constructing a body">

=item $obj-E<gt>B<eol>(['CR'|'LF'|'CRLF'|'NATIVE'])

See L<Mail::Message::Body/"Constructing a body">

=item $obj-E<gt>B<foreachComponent>(CODE)

Execute the CODE for each component of the message: the preamble, the
epilogue, and each of the parts.

Each component is a body and is passed as second argument to the CODE.
The first argument is a reference to this multi-parted body.  The CODE
returns a body object.  When any of the returned bodies differs from
the body which was passed, then a new multi-part body will be returned.
Reference to the not-changed bodies and the changed bodies will be
included in that new multi-part.

example: 

 my $checked = $multi->foreachComponent(sub {$_[1]->check});

=item $obj-E<gt>B<foreachLine>((CODE))

It is NOT possible to call some code for each line of a multipart,
because that would not only inflict damage to the body of each
message part, but also to the headers and the part separators.

=item $obj-E<gt>B<stripSignature>(OPTIONS)

Removes all parts which contains data usually defined as being signature.
The L<MIME::Type|MIME::Type> module provides this knowledge.  A new multipart is
returned, containing the remaining parts.  No OPTIONS are defined yet,
although some may be specified, because this method overrules the
C<stripSignature> method for normal bodies.

 -Option     --Defined in     --Default
  max_lines    Mail::Message::Body::Construct  10
  pattern      Mail::Message::Body::Construct  qr/^--\s?$/
  result_type  Mail::Message::Body::Construct  <same as current>

=over 2

=item max_lines => INTEGER|undef

=item pattern => REGEX|STRING|CODE

=item result_type => CLASS

=back

=item $obj-E<gt>B<unify>(BODY)

See L<Mail::Message::Body::Encode/"Constructing a body">

=back

=head2 The body

=over 4

=item $obj-E<gt>B<isDelayed>

See L<Mail::Message::Body/"The body">

=item $obj-E<gt>B<isMultipart>

See L<Mail::Message::Body/"The body">

=item $obj-E<gt>B<isNested>

See L<Mail::Message::Body/"The body">

=item $obj-E<gt>B<message>([MESSAGE])

See L<Mail::Message::Body/"The body">

=back

=head2 About the payload

=over 4

=item $obj-E<gt>B<charset>

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<checked>([BOOLEAN])

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<description>([STRING|FIELD])

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<disposition>([STRING|FIELD])

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<dispositionFilename>([DIRECTORY])

See L<Mail::Message::Body::Encode/"About the payload">

=item $obj-E<gt>B<isBinary>

See L<Mail::Message::Body::Encode/"About the payload">

=item $obj-E<gt>B<isText>

See L<Mail::Message::Body::Encode/"About the payload">

=item $obj-E<gt>B<mimeType>

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<nrLines>

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<size>

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<transferEncoding>([STRING|FIELD])

See L<Mail::Message::Body/"About the payload">

=item $obj-E<gt>B<type>([STRING|FIELD])

See L<Mail::Message::Body/"About the payload">

=back

=head2 Access to the payload

=over 4

=item $obj-E<gt>B<boundary>([STRING])

Returns the boundary which is used to separate the parts in this
body.  If none was read from file, then one will be assigned.  With
STRING you explicitly set the boundary to be used.

=item $obj-E<gt>B<endsOnNewline>

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<epilogue>

Returns the epilogue; the text after the last message part (after the
last real attachment).
The epilogue is stored in a BODY object, and its encoding is taken
from the general multipart header.

=item $obj-E<gt>B<file>

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<lines>

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<part>(INDEX)

Returns only the part with the specified INDEX.  You may use a negative
value here, which counts from the back in the list.  Parts which are
flagged to be deleted are included in the count.

example: 

 $message->body->part(2)->print;
 $body->part(1)->delete;

=item $obj-E<gt>B<parts>(['ALL'|'ACTIVE'|'DELETED'|'RECURSE'|FILTER])

Return all parts by default, or when ALL is specified.  C<ACTIVE> returns
the parts which are not flagged for deletion, as opposite to C<DELETED>.
C<RECURSE> descents into all nested multiparts to collect all parts.

You may also specify a code reference which is called for each nested
part.  The first argument will be the message part.  When the code
returns true, the part is incorporated in the return list.

example: 

 print "Number of attachments: ",
     scalar $message->body->parts('ACTIVE');

 foreach my $part ($message->body->parts) {
     print "Type: ", $part->get('Content-Type');
 }

=item $obj-E<gt>B<preamble>

Returns the preamble; the text before the first message part (before the
first real attachment).
The preamble is stored in a BODY object, and its encoding is taken
from the multipart header.

=item $obj-E<gt>B<print>([FILEHANDLE])

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<printEscapedFrom>(FILEHANDLE)

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<string>

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<stripTrailingNewline>

See L<Mail::Message::Body/"Access to the payload">

=item $obj-E<gt>B<write>(OPTIONS)

See L<Mail::Message::Body/"Access to the payload">

=back

=head2 Internals

=over 4

=item $obj-E<gt>B<addTransferEncHandler>(NAME, CLASS|OBJECT)

=item Mail::Message::Body::Multipart-E<gt>B<addTransferEncHandler>(NAME, CLASS|OBJECT)

See L<Mail::Message::Body::Encode/"Internals">

=item $obj-E<gt>B<contentInfoFrom>(HEAD)

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<contentInfoTo>(HEAD)

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<fileLocation>([BEGIN,END])

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<getTransferEncHandler>(TYPE)

See L<Mail::Message::Body::Encode/"Internals">

=item $obj-E<gt>B<isModified>

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<load>

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<modified>([BOOLEAN])

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<moveLocation>([DISTANCE])

See L<Mail::Message::Body/"Internals">

=item $obj-E<gt>B<read>(PARSER, HEAD, BODYTYPE [,CHARS [,LINES]])

See L<Mail::Message::Body/"Internals">

=back

=head2 Error handling

=over 4

=item $obj-E<gt>B<AUTOLOAD>

See L<Mail::Message::Body/"Error handling">

=item $obj-E<gt>B<addReport>(OBJECT)

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<defaultTrace>([LEVEL]|[LOGLEVEL, TRACELEVEL]|[LEVEL, CALLBACK])

=item Mail::Message::Body::Multipart-E<gt>B<defaultTrace>([LEVEL]|[LOGLEVEL, TRACELEVEL]|[LEVEL, CALLBACK])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<errors>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<log>([LEVEL [,STRINGS]])

=item Mail::Message::Body::Multipart-E<gt>B<log>([LEVEL [,STRINGS]])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<logPriority>(LEVEL)

=item Mail::Message::Body::Multipart-E<gt>B<logPriority>(LEVEL)

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<logSettings>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<notImplemented>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<report>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<reportAll>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<trace>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<warnings>

See L<Mail::Reporter/"Error handling">

=back

=head2 Cleanup

=over 4

=item $obj-E<gt>B<DESTROY>

See L<Mail::Reporter/"Cleanup">

=item $obj-E<gt>B<inGlobalDestruction>

See L<Mail::Reporter/"Cleanup">

=back

=head1 DIAGNOSTICS

=over 4

=item Warning: Charset $name is not known

The encoding or decoding of a message body encounters a character set which
is not understood by Perl's Encode module.

=item Error: Data not convertible to a message (type is $type)

An object which is not coercable into a L<Mail::Message::Part|Mail::Message::Part> object was
passed to the initiation.  The data is ignored.

=item Warning: No decoder defined for transfer encoding $name.

The data (message body) is encoded in a way which is not currently understood,
therefore no decoding (or recoding) can take place.

=item Warning: No encoder defined for transfer encoding $name.

The data (message body) has been decoded, but the required encoding is
unknown.  The decoded data is returned.

=item Error: Package $package does not implement $method.

Fatal error: the specific package (or one of its superclasses) does not
implement this method where it should. This message means that some other
related classes do implement this method however the class at hand does
not.  Probably you should investigate this and probably inform the author
of the package.

=item Error: Unknown criterium $what to select parts.

Valid choices fdr part selections are C<ALL>, C<ACTIVE>, C<DELETED>,
C<RECURSE> or a code reference.  However, some other argument was passed.

=item Warning: Unknown line terminator $eol ignored

=item Error: You cannot use foreachLine on a multipart

L<foreachLine()|Mail::Message::Body::Multipart/"METHODS"> should be used on decoded message bodies only, because
it would attempt to modify part-headers and separators as well, which is
clearly not acceptible.

=back

=head1 SEE ALSO

This module is part of Mail-Box distribution version 2.099,
built on July 07, 2011. Website: F<http://perl.overmeer.net/mailbox/>

=head1 LICENSE

Copyrights 2001-2011 by Mark Overmeer. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

