/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ros_core_ws/src/ros_comm/clients/roscpp/test_serialization/msg/ArrayOfFixedLength.msg
 *
 */


#ifndef ROSCPP_MESSAGE_ARRAYOFFIXEDLENGTH_H
#define ROSCPP_MESSAGE_ARRAYOFFIXEDLENGTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp/FixedLength.h>

namespace roscpp
{
template <class ContainerAllocator>
struct ArrayOfFixedLength_
{
  typedef ArrayOfFixedLength_<ContainerAllocator> Type;

  ArrayOfFixedLength_()
    : a()  {
    }
  ArrayOfFixedLength_(const ContainerAllocator& _alloc)
    : a()  {
      a.assign( ::roscpp::FixedLength_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::roscpp::FixedLength_<ContainerAllocator> , 4>  _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ArrayOfFixedLength_

typedef ::roscpp::ArrayOfFixedLength_<std::allocator<void> > ArrayOfFixedLength;

typedef boost::shared_ptr< ::roscpp::ArrayOfFixedLength > ArrayOfFixedLengthPtr;
typedef boost::shared_ptr< ::roscpp::ArrayOfFixedLength const> ArrayOfFixedLengthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp::ArrayOfFixedLength_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosgraph_msgs': ['/root/ros_core_ws/src/ros_comm/messages/rosgraph_msgs/msg'], 'std_msgs': ['/root/ros_core_ws/src/std_msgs/msg'], 'roscpp': ['/root/ros_core_ws/src/ros_comm/clients/roscpp/msg', '/root/ros_core_ws/src/ros_comm/clients/roscpp/test/msg', '/root/ros_core_ws/src/ros_comm/clients/roscpp/test_serialization/msg', '/root/ros_core_ws/src/ros_comm/clients/roscpp/perf/msg', '/root/ros_core_ws/src/ros_comm/clients/roscpp/perf_serialization/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "770e15962592d1fbea70b6b820ba16d9";
  }

  static const char* value(const ::roscpp::ArrayOfFixedLength_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x770e15962592d1fbULL;
  static const uint64_t static_value2 = 0xea70b6b820ba16d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp/ArrayOfFixedLength";
  }

  static const char* value(const ::roscpp::ArrayOfFixedLength_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This comment has \"quotes\" in it\n\
FixedLength[4] a\n\
================================================================================\n\
MSG: roscpp/FixedLength\n\
uint32 a\n\
float32 b\n\
\n\
";
  }

  static const char* value(const ::roscpp::ArrayOfFixedLength_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ArrayOfFixedLength_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp::ArrayOfFixedLength_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp::ArrayOfFixedLength_<ContainerAllocator>& v)
  {
    s << indent << "a[]" << std::endl;
    for (size_t i = 0; i < v.a.size(); ++i)
    {
      s << indent << "  a[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roscpp::FixedLength_<ContainerAllocator> >::stream(s, indent + "    ", v.a[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_MESSAGE_ARRAYOFFIXEDLENGTH_H
