=head1 NAME

Gtk2::Gdk::Event::GrabBroken

=cut

=for position post_hierarchy

=head1 HIERARCHY

  Gtk2::Gdk::Event
  +----Gtk2::Gdk::Event::GrabBroken

=cut




=head1 METHODS

=head2 window or undef = $event-E<gt>B<grab_window> ($newvalue=undef)

=over

=item * $newvalue (Gtk2::Gdk::Window or undef) 

=back

When you set a window into a GrabBroken event make sure you keep a
reference to it for as long as that event object or any copies exist,
because the event doesn't add its own reference.

Since: gtk+ 2.8

=head2 boolean = $event-E<gt>B<implicit> ($newvalue=0)

=over

=item * $newvalue (boolean) 

=back

Since: gtk+ 2.8

=head2 boolean = $event-E<gt>B<keyboard> ($newvalue=0)

=over

=item * $newvalue (boolean) 

=back

Since: gtk+ 2.8



=cut


=head1 SEE ALSO

L<Gtk2>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

