=head1 NAME

Gtk2::Gdk::Event::Property

=cut

=for position post_hierarchy

=head1 HIERARCHY

  Gtk2::Gdk::Event
  +----Gtk2::Gdk::Event::Property

=cut




=head1 METHODS

=head2 atom = $eventproperty-E<gt>B<atom> ($newvalue=0)

=over

=item * $newvalue (Gtk2::Gdk::Atom) 

=back

=head2 integer = $eventproperty-E<gt>B<state> ($newvalue=0)

=over

=item * $newvalue (integer) 

=back



=cut


=head1 SEE ALSO

L<Gtk2>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

