=head1 NAME

Mail::Message::Replace::MailHeader - fake Mail::Header

=head1 INHERITANCE

 Mail::Message::Replace::MailHeader
   is a Mail::Message::Head::Complete
   is a Mail::Message::Head
   is a Mail::Reporter

=head1 SYNOPSIS

 !!! ALPHA CODE !!!

 # change
 use Mail::Internet;
 use Mail::Header;
 # into
 use Mail::Message::Replace::MailInternet;
 # in existing code, and the code should still work, but
 # with the Mail::Message features.

=head1 DESCRIPTION

This module is a wrapper around a L<Mail::Message::Head::Complete|Mail::Message::Head::Complete>,
which simulates a L<Mail::Header> object.  The name-space of that module
is hijacked and many methods are added.

Most methods will work without any change, but you should test your
software again.  Small changes have been made to L<fold_length()|Mail::Message::Replace::MailHeader/"Simulating Mail::Header">,
L<header_hashref()|Mail::Message::Replace::MailHeader/"Simulating Mail::Header">.

=head1 OVERLOADED

=over 4

=item overload: B<"">

See L<Mail::Message::Head/"OVERLOADED">

=item overload: B<bool>

See L<Mail::Message::Head/"OVERLOADED">

=back

=head1 METHODS

=head2 Constructors

=over 4

=item $obj-E<gt>B<build>([PAIR|FIELD]-LIST)

See L<Mail::Message::Head::Complete/"Constructors">

=item $obj-E<gt>B<clone>([NAMES|ARRAY-OF-NAMES|REGEXS])

See L<Mail::Message::Head::Complete/"Constructors">

=item Mail::Message::Replace::MailHeader-E<gt>B<new>([ARG], OPTIONS)

The ARG is an array with header lines.

 -Option    --Defined in     --Default
  FoldLength                   79
  MailFrom                     'KEEP'
  Modify                       <false>
  field_type  Mail::Message::Head  Mail::Message::Field::Fast
  log         Mail::Reporter   'WARNINGS'
  message     Mail::Message::Head  undef
  modified    Mail::Message::Head  <false>
  trace       Mail::Reporter   'WARNINGS'

=over 2

=item FoldLength => INTEGER

=item MailFrom => 'IGNORE'|'ERROR'|'COERCE'|'KEEP'

How to handle the C<From > lines.  See L<mail_from()|Mail::Message::Replace::MailHeader/"Simulating Mail::Header">.

=item Modify => BOOLEAN

Reformat all header lines when they come in: change the folding.

=item field_type => CLASS

=item log => LEVEL

=item message => MESSAGE

=item modified => BOOLEAN

=item trace => LEVEL

=back

=back

=head2 The header

=over 4

=item $obj-E<gt>B<isDelayed>

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<isEmpty>

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<isModified>

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<knownNames>

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<message>([MESSAGE])

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<modified>([BOOLEAN])

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<nrLines>

See L<Mail::Message::Head::Complete/"The header">

=item $obj-E<gt>B<orderedFields>

See L<Mail::Message::Head/"The header">

=item $obj-E<gt>B<size>

See L<Mail::Message::Head::Complete/"The header">

=item $obj-E<gt>B<wrap>(INTEGER)

See L<Mail::Message::Head::Complete/"The header">

=back

=head2 Access to the header

=over 4

=item $obj-E<gt>B<add>(LINE, [INDEX])

Add a header line, which simply calls C<Mail::Message::Head::add()> on
the header for the specified LINE.  The INDEX is ignored, the unfolded
body of the field is returned.

=item $obj-E<gt>B<addListGroup>(OBJECT)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<addResentGroup>(RESENT-GROUP|DATA)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<addSpamGroup>(OBJECT)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<count>(NAME)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<delete>(TAG, [INDEX])

Delete the fields with the specified TAG.  The deleted fields are
returned.  If no index is given, then all are removed.

=item $obj-E<gt>B<get>(NAME, [INDEX])

Get all the header fields with the specified NAME.  In scalar context,
only the first fitting NAME is returned.  Even when only one NAME is
specified, multiple lines may be returned in list context: some fields
appear more than once in a header.

=item $obj-E<gt>B<grepNames>([NAMES|ARRAY-OF-NAMES|REGEXS])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<listGroup>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<names>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<print>([FILEHANDLE])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<printSelected>(FILEHANDLE, (STRING|REGEXP)s)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<printUndisclosed>([FILEHANDLE])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeContentInfo>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeField>(FIELD)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeFields>(STRING|REGEXP, [STRING|REGEXP, ...])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeFieldsExcept>(STRING|REGEXP, [STRING|REGEXP, ...])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeListGroup>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeResentGroups>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<removeSpamGroups>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<replace>(TAG, LINE, [INDEX])

Replace the field named TAG. from place INDEX (by default the first) by
the LINE.  When TAG is C<undef>, it will be extracted from the LINE first.
This calls L<Mail::Message::Head::Complete::reset()|Mail::Message::Head::Complete/"Access to the header"> on the message's head.

=item $obj-E<gt>B<resentGroups>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<reset>(NAME, FIELDS)

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<set>(FIELD | LINE | (NAME, BODY [,ATTRS]))

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<spamDetected>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<spamGroups>([NAMES])

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<string>

See L<Mail::Message::Head::Complete/"Access to the header">

=item $obj-E<gt>B<study>(NAME [,INDEX])

See L<Mail::Message::Head/"Access to the header">

=back

=head2 About the body

=over 4

=item $obj-E<gt>B<guessBodySize>

See L<Mail::Message::Head/"About the body">

=item $obj-E<gt>B<guessTimeStamp>

See L<Mail::Message::Head::Complete/"About the body">

=item $obj-E<gt>B<isMultipart>

See L<Mail::Message::Head/"About the body">

=item $obj-E<gt>B<recvstamp>

See L<Mail::Message::Head::Complete/"About the body">

=item $obj-E<gt>B<timestamp>

See L<Mail::Message::Head::Complete/"About the body">

=back

=head2 Internals

=over 4

=item $obj-E<gt>B<addNoRealize>(FIELD)

See L<Mail::Message::Head/"Internals">

=item $obj-E<gt>B<addOrderedFields>(FIELDS)

See L<Mail::Message::Head/"Internals">

=item $obj-E<gt>B<createFromLine>

See L<Mail::Message::Head::Complete/"Internals">

=item $obj-E<gt>B<createMessageId>

See L<Mail::Message::Head::Complete/"Internals">

=item $obj-E<gt>B<fileLocation>

See L<Mail::Message::Head/"Internals">

=item $obj-E<gt>B<load>

See L<Mail::Message::Head/"Internals">

=item $obj-E<gt>B<messageIdPrefix>([PREFIX, [HOSTNAME]|CODE])

=item Mail::Message::Replace::MailHeader-E<gt>B<messageIdPrefix>([PREFIX, [HOSTNAME]|CODE])

See L<Mail::Message::Head::Complete/"Internals">

=item $obj-E<gt>B<moveLocation>(DISTANCE)

See L<Mail::Message::Head/"Internals">

=item $obj-E<gt>B<setNoRealize>(FIELD)

See L<Mail::Message::Head/"Internals">

=back

=head2 Error handling

=over 4

=item $obj-E<gt>B<AUTOLOAD>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<addReport>(OBJECT)

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<defaultTrace>([LEVEL]|[LOGLEVEL, TRACELEVEL]|[LEVEL, CALLBACK])

=item Mail::Message::Replace::MailHeader-E<gt>B<defaultTrace>([LEVEL]|[LOGLEVEL, TRACELEVEL]|[LEVEL, CALLBACK])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<errors>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<log>([LEVEL [,STRINGS]])

=item Mail::Message::Replace::MailHeader-E<gt>B<log>([LEVEL [,STRINGS]])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<logPriority>(LEVEL)

=item Mail::Message::Replace::MailHeader-E<gt>B<logPriority>(LEVEL)

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<logSettings>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<notImplemented>

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<report>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<reportAll>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<trace>([LEVEL])

See L<Mail::Reporter/"Error handling">

=item $obj-E<gt>B<warnings>

See L<Mail::Reporter/"Error handling">

=back

=head2 Cleanup

=over 4

=item $obj-E<gt>B<DESTROY>

See L<Mail::Reporter/"Cleanup">

=item $obj-E<gt>B<inGlobalDestruction>

See L<Mail::Reporter/"Cleanup">

=back

=head2 Access to the header

=head2 Simulating Mail::Header

=over 4

=item $obj-E<gt>B<as_string>

Returns the whole header as one big scalar.
Calls L<Mail::Message::Head::Complete::string()|Mail::Message::Head::Complete/"Access to the header">.

=item $obj-E<gt>B<cleanup>

Cleanup memory usage.  Not needed here.

=item $obj-E<gt>B<combine>(TAG, [WITH])

I do not see any valid reason for this command, so did not implement it.

=item $obj-E<gt>B<dup>

Duplicate the header, which is simply L<clone()|Mail::Message::Head::Complete/"Constructors">.

=item $obj-E<gt>B<empty>

Clean-out the whole hash. Better not use this (simply create another
header object), although it should work.

=item $obj-E<gt>B<exists>

Returns whether there are any fields.

=item $obj-E<gt>B<extract>(ARRAY)

Extract (and remove) header fields from the array.

=item $obj-E<gt>B<fold>([LENGTH])

Refold all fields in the header, to LENGTH or whatever L<fold_length()|Mail::Message::Replace::MailHeader/"Simulating Mail::Header">
returns.

=item $obj-E<gt>B<fold_length>([[TAG], LENGTH])

Returns the line wrap, optionally after setting it to LENGTH.  The
old value is returned.  The TAG argument is ignored, because it is
silly to have different lines fold in different ways.  This method
cannot be called statically anymore.

=item $obj-E<gt>B<header>([ARRAY])

Extract the fields from the ARRAY, if specified, and then fold the fields.
Returned is an array with all fields, produced via L<orderedFields()|Mail::Message::Head/"The header">.

=item $obj-E<gt>B<header_hashref>(HASH)

If you are using this method, you must be stupid... anyway: I do not want to
support it for now: use L<add()|Mail::Message::Replace::MailHeader/"Access to the header"> and friends.

=item $obj-E<gt>B<mail_from>(['IGNORE'|'ERROR'|'COERCE'|'KEEP'])

What to do when a header line in the form `From ' is encountered. Valid
values are C<IGNORE> - ignore and discard the header, C<ERROR> - invoke
an error (call die), C<COERCE> - rename them as Mail-From and C<KEEP>
- keep them.

=item $obj-E<gt>B<modify>([BOOLEAN])

Refold the headers when they are added.

=item $obj-E<gt>B<read>(FILE)

Read the header from the FILE.

=item $obj-E<gt>B<tags>

Returns all the names of fields, implemented by
L<Mail::Message::Head::Complete::names()|Mail::Message::Head::Complete/"Access to the header">.

=item $obj-E<gt>B<unfold>([TAG])

Remove the folding for all instances of TAG, or all fields at once.

=back

=head2 The nasty bits

=over 4

=item $obj-E<gt>B<isa>(CLASS)

=item Mail::Message::Replace::MailHeader-E<gt>B<isa>(CLASS)

Of course, the C<isa()> class inheritance check should not see our
nasty trick.

=back

=head1 DIAGNOSTICS

=over 4

=item Warning: Cannot remove field $name from header: not found.

You ask to remove a field which is not known in the header.  Using
L<delete()|Mail::Message::Replace::MailHeader/"Access to the header">, L<reset()|Mail::Message::Head::Complete/"Access to the header">, or L<set()|Mail::Message::Head::Complete/"Access to the header"> to do the job will not result
in warnings: those methods check the existence of the field first.

=item Warning: Field objects have an implied name ($name)

=item Error: Package $package does not implement $method.

Fatal error: the specific package (or one of its superclasses) does not
implement this method where it should. This message means that some other
related classes do implement this method however the class at hand does
not.  Probably you should investigate this and probably inform the author
of the package.

=back

=head1 SEE ALSO

This module is part of Mail-Box distribution version 2.099,
built on July 07, 2011. Website: F<http://perl.overmeer.net/mailbox/>

=head1 LICENSE

Copyrights 2001-2011 by Mark Overmeer. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

