--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
- !ruby/struct:SM::Flow::P 
  body: Indicates no such domain was found.
constants: []

full_name: Resolv::DNS::Config::NXDomain
includes: []

instance_methods: []

name: NXDomain
superclass: ResolvError
