=head1 NAME

Gtk2::Gdk::PangoRenderer - wrapper for GdkPangoRenderer

=cut

=head1 HIERARCHY

  Glib::Object
  +----Pango::Renderer
       +----Gtk2::Gdk::PangoRenderer



=cut


=head1 METHODS

=head2 renderer = Gtk2::Gdk::PangoRenderer-E<gt>B<new> ($screen)

=over

=item * $screen (Gtk2::Gdk::Screen) 

=back

=head2 renderer = Gtk2::Gdk::PangoRenderer-E<gt>B<get_default> ($screen)

=over

=item * $screen (Gtk2::Gdk::Screen) 

=back

=head2 $gdk_renderer-E<gt>B<set_drawable> ($drawable)

=over

=item * $drawable (Gtk2::Gdk::Drawable or undef) 

=back

=head2 $gdk_renderer-E<gt>B<set_gc> ($gc)

=over

=item * $gc (Gtk2::Gdk::GC or undef) 

=back

=head2 $gdk_renderer-E<gt>B<set_override_color> ($part, $color)

=over

=item * $part (Pango::RenderPart) 

=item * $color (Gtk2::Gdk::Color or undef) 

=back

=head2 $gdk_renderer-E<gt>B<set_stipple> ($part, $stipple)

=over

=item * $part (Pango::RenderPart) 

=item * $stipple (Gtk2::Gdk::Bitmap or undef) 

=back



=cut


=head1 PROPERTIES

=over

=item 'screen' (Gtk2::Gdk::Screen : default undef : readable / writable / construct-only / private)

the GdkScreen for the renderer

=back



=cut


=head1 ENUMS AND FLAGS

=head2 enum Pango::RenderPart

=over

=item * 'foreground' / 'PANGO_RENDER_PART_FOREGROUND'

=item * 'background' / 'PANGO_RENDER_PART_BACKGROUND'

=item * 'underline' / 'PANGO_RENDER_PART_UNDERLINE'

=item * 'strikethrough' / 'PANGO_RENDER_PART_STRIKETHROUGH'

=back




=cut


=head1 SEE ALSO

L<Gtk2>, L<Glib::Object>, L<Pango::Renderer>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

