=head1 NAME

Gtk2::Gdk::PixbufFormat

=cut


=head1 METHODS

=head2 $format-E<gt>B<set_disabled> ($disabled)

=over

=item * $disabled (boolean) 

=back


Note that any change caused by this method will not immediately affect
I<$format-E<gt>{is_disabled}>.  You need to refetch the format in order to see
the new value.


Since: gtk+ 2.6



=cut


=head1 SEE ALSO

L<Gtk2>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

