=head1 NAME

Gtk2::Gdk::X11

=cut


=head1 METHODS

=head2 integer = Gtk2::Gdk::X11-E<gt>B<get_default_screen> 

=head2 Gtk2::Gdk::X11-E<gt>B<grab_server> 

=head2 boolean = Gtk2::Gdk::X11-E<gt>B<net_wm_supports> ($property)

=over

=item * $property (Gtk2::Gdk::Atom) 

=back

=head2 unsigned = Gtk2::Gdk::X11-E<gt>B<get_server_time> ($window)

=over

=item * $window (Gtk2::Gdk::Window) 

=back

=head2 Gtk2::Gdk::X11-E<gt>B<ungrab_server> 



=cut


=head1 SEE ALSO

L<Gtk2>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2008 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Gtk2> for a full notice.



=cut

