/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /root/ros_core_ws/src/ros_tutorials/turtlesim/srv/SetPen.srv
 *
 */


#ifndef TURTLESIM_MESSAGE_SETPEN_H
#define TURTLESIM_MESSAGE_SETPEN_H

#include <ros/service_traits.h>


#include <turtlesim/SetPenRequest.h>
#include <turtlesim/SetPenResponse.h>


namespace turtlesim
{

struct SetPen
{

typedef SetPenRequest Request;
typedef SetPenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen
} // namespace turtlesim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim::SetPen > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::turtlesim::SetPen&) { return value(); }
};

template<>
struct DataType< ::turtlesim::SetPen > {
  static const char* value()
  {
    return "turtlesim/SetPen";
  }

  static const char* value(const ::turtlesim::SetPen&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim::SetPenRequest> should match 
// service_traits::MD5Sum< ::turtlesim::SetPen > 
template<>
struct MD5Sum< ::turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SetPenRequest> should match 
// service_traits::DataType< ::turtlesim::SetPen > 
template<>
struct DataType< ::turtlesim::SetPenRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim::SetPenResponse> should match 
// service_traits::MD5Sum< ::turtlesim::SetPen > 
template<>
struct MD5Sum< ::turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim::SetPenResponse> should match 
// service_traits::DataType< ::turtlesim::SetPen > 
template<>
struct DataType< ::turtlesim::SetPenResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim::SetPen >::value();
  }
  static const char* value(const ::turtlesim::SetPenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_MESSAGE_SETPEN_H
