set(SHAREDDESKTOPONTOLOGIES_VERSION_MAJOR 0)
set(SHAREDDESKTOPONTOLOGIES_VERSION_MINOR 8)
set(SHAREDDESKTOPONTOLOGIES_VERSION_RELEASE 1)
set(SHAREDDESKTOPONTOLOGIES_VERSION 0.8.1)

set(SHAREDDESKTOPONTOLOGIES_ROOT_DIR /usr/share/ontology)
