/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/ros_core_ws/src/ros_comm/tools/rosbag/bag_migration_tests/msg_current/Converged.msg
 *
 */


#ifndef ROSBAG_MESSAGE_CONVERGED_H
#define ROSBAG_MESSAGE_CONVERGED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rosbag/SimpleMigrated.h>

namespace rosbag
{
template <class ContainerAllocator>
struct Converged_
{
  typedef Converged_<ContainerAllocator> Type;

  Converged_()
    : field1()
    , field2()  {
      field1.assign(0.0);
  }
  Converged_(const ContainerAllocator& _alloc)
    : field1()
    , field2()  {
      field1.assign(0.0);

      field2.assign( ::rosbag::SimpleMigrated_<ContainerAllocator> (_alloc));
  }



   typedef boost::array<float, 4>  _field1_type;
  _field1_type field1;

   typedef boost::array< ::rosbag::SimpleMigrated_<ContainerAllocator> , 4>  _field2_type;
  _field2_type field2;




  typedef boost::shared_ptr< ::rosbag::Converged_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosbag::Converged_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Converged_

typedef ::rosbag::Converged_<std::allocator<void> > Converged;

typedef boost::shared_ptr< ::rosbag::Converged > ConvergedPtr;
typedef boost::shared_ptr< ::rosbag::Converged const> ConvergedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosbag::Converged_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosbag::Converged_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosbag

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosgraph_msgs': ['/root/ros_core_ws/src/ros_comm/messages/rosgraph_msgs/msg'], 'std_msgs': ['/root/ros_core_ws/src/std_msgs/msg'], 'rosbag': ['/root/ros_core_ws/src/ros_comm/tools/rosbag/bag_migration_tests/msg_current']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosbag::Converged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosbag::Converged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosbag::Converged_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosbag::Converged_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosbag::Converged_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosbag::Converged_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosbag::Converged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb364bc8a2a4b0b810763576f44bc36d";
  }

  static const char* value(const ::rosbag::Converged_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb364bc8a2a4b0b8ULL;
  static const uint64_t static_value2 = 0x10763576f44bc36dULL;
};

template<class ContainerAllocator>
struct DataType< ::rosbag::Converged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosbag/Converged";
  }

  static const char* value(const ::rosbag::Converged_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosbag::Converged_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4]           field1 # [1.2, 3.4, 5.6, 7.8]\n\
SimpleMigrated[4]    field2 # [11, 22, 33, 44]\n\
================================================================================\n\
MSG: rosbag/SimpleMigrated\n\
int32 data # 42\n\
";
  }

  static const char* value(const ::rosbag::Converged_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosbag::Converged_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.field1);
      stream.next(m.field2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Converged_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosbag::Converged_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosbag::Converged_<ContainerAllocator>& v)
  {
    s << indent << "field1[]" << std::endl;
    for (size_t i = 0; i < v.field1.size(); ++i)
    {
      s << indent << "  field1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.field1[i]);
    }
    s << indent << "field2[]" << std::endl;
    for (size_t i = 0; i < v.field2.size(); ++i)
    {
      s << indent << "  field2[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rosbag::SimpleMigrated_<ContainerAllocator> >::stream(s, indent + "    ", v.field2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSBAG_MESSAGE_CONVERGED_H
